name: Publish Docker image
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v2
      - name: get project version
        id: get_version
        run: |
          echo ::set-output name=version_tag::$(awk -F'[ ="]+' '$1 == "version" { print $2 }' pyproject.toml)
          echo "project version - v${{ steps.get_version.outputs.version_tag }}"
      - name: version dockerfile
        run: sed -i 's/v0.0.0/v${{ steps.get_version.outputs.version_tag}}/g' Dockerfile
      - name: set up Docker builder
        uses: docker/setup-buildx-action@v1
      - name: log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: push to Github Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/vyvy-vi/uwus-online:v${{ steps.get_version.outputs.version_tag}}
            ghcr.io/vyvy-vi/uwus-online:latest
